### ISSUE TITLE
What about Docker:)

### ISSUE THREAD

**Issue by JinweiClarkChao** [ZJU-NewMirrors/IssueTracker#3]
As you know, pulling images from https://registry.hub.docker.com/ is quite slow in mainland China. So what about adding Docker repos into ZJUmirrors? Something like [DaoCloud](https://www.daocloud.io/)?

**Comment by jamesruan** [comment]
npm mirror just hit the spot.

I'm interested in the so-called "VM and a management system". Any details? Why not just using docker?

**Comment by JinweiClarkChao** [comment]
Docker supports private registry. Can we build docker mirror upon that if we handle the access permissions correctly? 
It sounds like a more "dockerized" way:smiley:

**Comment by DelightRun** [comment]
+1 for Docker support.
At present we have to use Tsinghua Tuna's docker mirrors.
