### ISSUE TITLE
能不能添加对Andoid SDK的支持呢？

### ISSUE THREAD

**Issue by Shuailong** [ZJU-NewMirrors/IssueTracker#4]
你好，浙大镜像方便了包括我在内的很多人，我非常喜欢。但是发现没有ANdroid SDK的支持。而Android官方的下载实在是太慢，所以能不能像东软学院这个.. mirrors.neusoft.edu.cn，加入安卓的SDK呢？谢谢！

**Comment by vxst** [comment]
是指Android这个子目录吗？看起来好像只有305个文件，不知道是不是你指的SDK？

**Comment by Shuailong** [comment]
是的，里面包含了安卓开发所必需的各种工具和文件。

**Comment by JinweiClarkChao** [comment]
同步Android SDK会涉及到版权原因吗？因为看到[TUNA镜像源](http://mirrors.tuna.tsinghua.edu.cn/)上提到了这一点。
`因版权原因，我们无法提供 Android SDK 镜像。`

**Comment by bubbleatgit** [comment]
@Shuailong  http://mirrors.tuna.tsinghua.edu.cn/help/#AOSP 清华大学镜像站有个AOSP，貌似能解决你的问题

**Comment by JinweiClarkChao** [comment]
@bubbleatgit 
@Shuailong 指的应该是Android SDK，例如 http://mirrors.neusoft.edu.cn/android/repository/  这些，和AOSP是不同的。可以参看http://forum.xda-developers.com/showthread.php?t=2064723

**Comment by bubbleatgit** [comment]
这个我也不是很清楚
@JinweiClarkChao 管理这么晚还在.

**Comment by JinweiClarkChao** [comment]
@bubbleatgit 误会了，我不是管理。

**Comment by bubbleatgit** [comment]
哦哦

**Comment by vxst** [comment]
Android SDK不镜像主要是由于版权问题，USTC和Tsinghua也因为类似问题没有做Android SDK镜像。

**Comment by bubbleatgit** [comment]
了解了
