### ISSUE TITLE
配置生成器BUG，不能生成 openSUSE 配置文件

### ISSUE THREAD

**Issue by Overvenus** [ZJU-NewMirrors/IssueTracker#5]
[mirrors.zju.edu.cn](http://mirrors.zju.edu.cn/) 中的配置生成器无法生成 openSUSE 配置文件。

BTW, ubuntu 系列也可以像 mint 一样提示去 Software & Updates 里选择 ```mirrors.zju.edu.cn```.

谢谢！ :+1:

**Comment by vxst** [comment]
已修复了，不过好像目前并不在OpenSUSE的官方列表里所以步骤暂时不适用与13.2，正在与OpenSUSE联系增加列表
