### ISSUE TITLE
希望增加gitlab-ce omnibus仓库

### ISSUE THREAD

**Issue by bubbleatgit** [ZJU-NewMirrors/IssueTracker#6]
https://packages.gitlab.com/gitlab/gitlab-ce/mirror

**Comment by vxst** [comment]
好的，会在最近一周添加

**Comment by bubbleatgit** [comment]
@vxst 楼主万岁

**Comment by bubbleatgit** [comment]
静候vxst佳音

**Comment by vxst** [comment]
由于packagecloud提供的方法需要多套系统（Debian系和RHEL系），比较麻烦，现正在联系源管理员询问是否有直接rsync的源可用；否则的话就需要使用container。会需要一些时间。

**Comment by vxst** [comment]
据说他们会在开会时讨论zz
https://gitlab.com/gitlab-org/omnibus-gitlab/issues/960

**Comment by bubbleatgit** [comment]
静待佳音

**Comment by vxst** [comment]
已完成

**Comment by bubbleatgit** [comment]
已经收到，感谢浙大开源镜像

2016-03-08 17:14 GMT+08:00 Shan Thomas <notifications@github.com>:

**Comment by bubbleatgit** [comment]
https://mirrors.tuna.tsinghua.edu.cn/help/gitlab-ce/  TUNA的帮助文档。我看浙大镜像站没有帮助。

2016-03-10 16:03 GMT+08:00 张凯旋 <tingshow163@gmail.com>:
