### ISSUE TITLE
CTAN 源更新

### ISSUE THREAD

**Issue by ryecao** [ZJU-NewMirrors/IssueTracker#7]
你们好，TeXLive 2015 出了也有一段时间了，然而 CTAN 源好像一直没有更新过，希望能更新一下。
感谢你们的工作 : )

**Comment by vxst** [comment]
已更新，现在CTAN的上游源已修复，同步频率也由原先的一周一次改到每日一次。

**Comment by vxst** [comment]
请测试，如果没有问腿的话就把这个Issue关掉了

**Comment by ryecao** [comment]
好的，非常感谢！
