### ISSUE TITLE
希望增加 Mozilla 的软件仓库镜像

### ISSUE THREAD

**Issue by wbsdty331** [ZJU-NewMirrors/IssueTracker#8]
http://ftp.mozilla.org/pub/ 

这个是 Firefox 的软件仓库，包括 ThunderBird / Firefox 之类的软件都可以直接从 FTP 上面下载。以前国内也有几个镜像，但是自从 Mozilla 说过了他们在 FTP 上面使用了 CDN 之后，很多都撤销了

但是 Mozilla 现在用的是 Amazon S3 的服务器，在国内访问情况堪忧，下载速度也非常的缓慢

希望能增加，谢谢！

**Comment by vxst** [comment]
太大了，放不下。

像ThunderBird每一个软件版本发布都包含linux i686/linux x86-64/mac/win32的59种语言的二进制包和更新包，而这472个包都是不同的，对于大部分版本每个小版本更新都会产生总大小约40G的文件，光ThunderBird一项就将近有6T的空间，FireFox之类的情况类似；整个ftp将近有数十T的内容，mirrors的存储机柜剩余空间不足以容纳mozilla镜像。

**Comment by vxst** [comment]
而且Mozilla用的是Amazon Cloudfront CDN，在国内基本上是用香港站点，也没有那么不堪...我在电信和网通线路上做的测试都可以达到线路的满速度，校内测试能达到5.58MB/s，应该也是可以接受的了，从速度上讲也不需要镜像。
